substitutions:
  _REGION: us-central1
  _REPOSITORY: xpex-academy-staging
  _IMAGE: xpex-academy-api
  _TAG: staging-manual
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'apps/api/Dockerfile', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}', 'apps/api']
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'
