'use client'

import Link from 'next/link'
import { Bell, ChevronDown, Menu, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { xpexNavigation } from './xpex-navigation'
import type { XpexRole } from './xpex-types'
import './xpex.css'

const identities = { aluno: ['Estudante Demo', 'Área do aluno'], professora: ['Professora Kelle', 'Coordenadora e Professora'], polo: ['Kelle Digital Lab', 'Polo piloto'] } as const

function Brand() { return <Link href="/" className="flex items-center gap-3 rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500"><span className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-orange-500 to-orange-600 font-black text-white shadow-[0_0_28px_rgba(255,106,0,.28)]">XP</span><span><strong className="block tracking-[.18em] text-white">XpeX</strong><small className="text-[10px] font-semibold uppercase tracking-[.24em] text-slate-500">Academy</small></span></Link> }

export function XpexAppShell({ role, children }: { role: XpexRole; children: ReactNode }) {
  const [open, setOpen] = useState(false)
  const [name, subtitle] = identities[role]
  return <div className="xpex-root min-h-screen text-slate-100"><a href="#conteudo-beta" className="xpex-skip">Pular para o conteúdo</a>{open && <button aria-label="Fechar navegação" className="fixed inset-0 z-30 bg-black/70 lg:hidden" onClick={() => setOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-white/10 bg-[#050d18]/95 p-5 backdrop-blur-xl transition-transform ${open ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0`}><div className="flex items-center justify-between"><Brand /><button aria-label="Fechar menu" onClick={() => setOpen(false)} className="xpex-icon-button lg:hidden"><X size={19} /></button></div><p className="mt-9 px-3 text-[10px] font-bold uppercase tracking-[.24em] text-slate-600">Navegação</p><nav className="mt-3 space-y-1 overflow-y-auto" aria-label={`Navegação — ${subtitle}`}>{xpexNavigation[role].map(({ label, icon: Icon, href }, index) => <a key={label} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 ${index === 0 ? 'border border-blue-400/15 bg-blue-500/10 font-bold text-cyan-200' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon size={17} />{label}</a>)}</nav><div className="mt-auto rounded-2xl border border-orange-500/20 bg-orange-500/[.06] p-4"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-orange-400">Preview Beta</p><p className="mt-2 text-xs leading-5 text-slate-400">Ambiente de apresentação. Todos os indicadores são fictícios e não persistem.</p></div></aside>
    <div className="lg:pl-72"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#02050b]/85 px-4 py-3 backdrop-blur-xl md:px-8"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><button aria-label="Abrir menu" onClick={() => setOpen(true)} className="xpex-icon-button lg:hidden"><Menu size={20} /></button><div className="hidden lg:block"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-cyan-400">XpeX Experience</p><p className="text-sm font-semibold text-slate-300">{subtitle}</p></div><div className="flex items-center gap-2"><nav className="hidden gap-1 rounded-xl border border-white/10 bg-white/[.03] p-1 sm:flex" aria-label="Alternar experiência">{(['aluno','professora','polo'] as XpexRole[]).map(item => <Link key={item} href={`/beta/${item}`} className={`rounded-lg px-3 py-2 text-xs font-bold capitalize ${item === role ? 'bg-orange-500 text-white' : 'text-slate-400 hover:text-white'}`}>{item}</Link>)}</nav><button className="xpex-icon-button" aria-label="Notificações demonstrativas"><Bell size={18} /></button><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] p-1.5 pr-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-blue-500 to-cyan-400 text-xs font-black text-white">{name.slice(0,2).toUpperCase()}</span><span className="hidden text-xs font-bold text-white md:block">{name}</span><ChevronDown className="text-slate-500" size={14} /></div></div></div></header><main id="conteudo-beta" className="mx-auto max-w-[1440px] p-4 md:p-8">{children}<footer className="mt-10 border-t border-white/10 py-6 text-xs text-slate-500">XpeX Academy • Experiência demonstrativa • Motor open-source LearnHouse preservado sob AGPL-3.0</footer></main></div></div>
}
