name: API Lint
on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/**"
  pull_request:
    paths:
      - "apps/api/**"
permissions:
  contents: read
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          src: "./apps/api"
          args: >-
            check
            --extend-per-file-ignores=apps/api/config/config.py:I001
            --extend-per-file-ignores=apps/api/config/config.py:UP045
